### ISSUE TITLE
Request: Save button on hover image

### ISSUE THREAD

**Issue by Mef45** [nirewen/Quicksave#2]
Hi.
Can you add save button on hover image, like in original plugin?

Top left corner. There's should be save icon, but this image "died" and now just 404. But this feature was useful.
![image](https://user-images.githubusercontent.com/26562037/34859471-2d420d20-f778-11e7-85a7-820241924f0f.png)

**Comment by nirewen** [comment]
Maybe I'll just add the Save button to the context menu. Would be more subtle, I don't know.
What do you think?

**Comment by Mef45** [comment]
Yeah, i think that would be nice.
