### ISSUE TITLE
Quick Save Issue

### ISSUE THREAD

**Issue by CilithFurr** [nirewen/Quicksave#3]
I am currently unable to use the Quicksave function, I tried updated it/reinstalling it. Nothing works, may be an issue due to a discord api update.
![discord_2018-01-17_18-42-59](https://user-images.githubusercontent.com/35547997/35074994-51046b30-fbb6-11e7-9c9d-008b1b5f0c63.png)

**Comment by Thewishmaker** [comment]
This quicksave plugin has the button below the image when you enlarge it.
![image](https://user-images.githubusercontent.com/34527063/35180689-73f7268a-fd7a-11e7-9611-0b4da7b3f13a.png)
