### ISSUE TITLE
First image always saves as 'image0'

### ISSUE THREAD

**Issue by MildPanda** [nirewen/Quicksave#32]
![discord_lx943em0f2](https://user-images.githubusercontent.com/5686244/48677843-dc7d7580-eb2f-11e8-9817-9d2f1cc938f6.png)

Just tried to change the filename length to see if that'd fix it but anytime I save an image, if I don't have any files already saved through the plugin the first file is always 'Image0' instead of gibberish like '3fsweh'

**Comment by nirewen** [comment]
This doesn't look like my plugin but ok. Mine used to have a better UI :eyes:
I can take a look at this issue. Maybe it's about the images you sent using an iPhone or mobile, because you can send multiple files there

**Comment by MildPanda** [comment]
Oof, my bad. This is kosshi's save plugin. I'm just saving the image from discord and the first image always seems to save as Image0 if there isn't an existing image0 so it wouldn't really cause a problem but gets annoying when you move them to a different folder and there may already be an image0 inside that. I'll post it over on his github, sorry about that.
